import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Script from 'next/script';
import { Modal } from '@/components/modal';
import { Toast } from '@/components/toast';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en " className={`${geistSans.variable} antialiased`}>
      <head>
        <Script
          src={`${process.env.MIDTRANS_URL}/snap/snap.js`}
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
        />
      </head>
      <body className="font-sans">
        {children}
        <Toast />
        <Modal />
      </body>
    </html>
  );
}
